// Ported from cordon crates/bpf-common/src/layout.rs @ b40a8c7 (Apache-2.0) — unchanged apart from the crate rename.
//! Compile-time struct-layout helpers and the [`padded_pod!`] macro.
//!
//! The POD types shared with the eBPF program are written into BPF maps by a raw byte
//! copy (aya takes a `&[u8]` byte-view over the value for `bpf_map_update_elem`). Two
//! things must hold for that to be sound and stable:
//!  - **Fully initialized** — a byte-view over *uninitialized* padding is UB, so the value
//!    may have no uninitialized bytes; and for a map **key**, BPF hashes/compares the whole
//!    byte span, so stray padding bytes split one logical key across buckets.
//!  - **Deterministic** — the same logical value should produce the same bytes (no stack
//!    garbage in the gaps), so an in-map image is reproducible.
//!
//! [`padded_pod!`] gives both: it appends an **auto-sized, always-zeroed trailing `_pad`**
//! that rounds the struct up to its alignment (so the value is fully initialized), and it
//! emits a `const` assertion that there is **no interior padding** — the one thing the
//! trailing pad can't fill. So a field reorder that opens an interior gap fails the *build*,
//! not a test. Field *order* is still yours to choose (lay fields out large-to-small to stay
//! gap-free); the macro only sizes the trailing pad and proves the result is byte-for-byte
//! packed.

/// The `(size, align)` of a field type — fed one-per-field into [`trailing_pad`] by the
/// [`padded_pod!`] expansion. Const, so it runs at compile time where sizes are known (a
/// proc-macro, working on tokens, could not see them).
pub(crate) const fn field<T>() -> (usize, usize) {
    (core::mem::size_of::<T>(), core::mem::align_of::<T>())
}

/// Round `n` up to the next multiple of `align` (a power-of-two alignment, always ≥ 1).
const fn round_up(n: usize, align: usize) -> usize {
    n.div_ceil(align) * align
}

/// The trailing pad bytes a `#[repr(C)]` struct with these `(size, align)` fields needs to
/// round its total size up to its own alignment — replicating the `repr(C)` layout walk
/// (place each field at the next multiple of its alignment; the struct's alignment is the
/// max field alignment). Returns only the **trailing** gap; interior gaps are caught by the
/// [`padded_pod!`] assertion instead, since this can't fill them.
pub(crate) const fn trailing_pad(fields: &[(usize, usize)]) -> usize {
    let mut off = 0;
    let mut max_align = 1;
    let mut i = 0;
    while i < fields.len() {
        let (size, align) = fields[i];
        off = round_up(off, align) + size;
        if align > max_align {
            max_align = align;
        }
        i += 1;
    }
    round_up(off, max_align) - off
}

/// Declare a `#[repr(C)]` POD struct with an **auto-sized, zeroed trailing `_pad`** and a
/// compile-time **no-interior-padding** guarantee (see the module docs for why both matter).
///
/// The appended `_pad` is `[u8; Self::PAD]`; construct it as `_pad: [0; Self::PAD]` (when
/// `PAD == 0` that is just `[0; 0]`, an empty array, so the pattern is uniform). The macro
/// fills only the *trailing* gap — it cannot insert *interior* padding, so it instead
/// `assert!`s there is none, turning a bad field order into a build error.
///
/// Pass attributes (`#[repr(C)]`, `#[derive(…)]`) and per-field doc comments through as
/// usual; the derives apply to the generated `_pad` too (`[u8; N]` is `Copy`/`Eq`/`Hash`/… ).
macro_rules! padded_pod {
    (
        $(#[$meta:meta])*
        $vis:vis struct $name:ident {
            $(
                $(#[$fmeta:meta])*
                $fvis:vis $fname:ident : $fty:ty
            ),* $(,)?
        }
    ) => {
        $(#[$meta])*
        $vis struct $name {
            $(
                $(#[$fmeta])*
                $fvis $fname: $fty,
            )*
            /// Auto-sized, always-zeroed trailing pad (generated by `padded_pod!`): rounds
            /// the value up to its alignment so it carries **no uninitialized bytes** — the
            /// byte-view aya copies into the BPF map is sound and deterministic, and (for a
            /// key) hashes consistently. Constructors set it `[0; Self::PAD]`; the kernel
            /// never reads it.
            $vis _pad: [u8; $name::PAD],
        }

        impl $name {
            /// Length of the generated trailing [`_pad`](Self::_pad), for constructors
            /// (`_pad: [0; Self::PAD]`). Computed from the field types' sizes/alignments.
            $vis const PAD: usize =
                $crate::layout::trailing_pad(&[$( $crate::layout::field::<$fty>() ),*]);
        }

        // The trailing pad rounds size up to alignment; assert there is no *interior* gap
        // (which it can't fill), so the type is byte-for-byte packed. A reorder that opens a
        // gap fails the build right here.
        const _: () = assert!(
            ::core::mem::size_of::<$name>()
                == (0 $( + ::core::mem::size_of::<$fty>() )*) + $name::PAD,
            concat!(
                stringify!($name),
                ": interior padding — reorder fields (large-to-small) so the type is packed"
            ),
        );
    };
}
