#!/bin/bash

echo "[ ] Post-Remove script [arg1='$1' arg2='$2']"

# DEB argument on upgrade - 'upgrade'; RPM - '1'
if [ "$1" = "upgrade" ] || [ "$1" = "1" ] ; then
    echo "[ ] Post-Remove script: This is an upgrade."
    exit 0
fi

#
# Remove selinux permissions for filemaster-core if we have semanage available.
#
if command -V semanage >/dev/null 2>&1; then
    echo "[ ] Removing SELinux permissions"
    semanage fcontext --delete /opt/filemaster/filemaster-core || :
    restorecon -R /opt/filemaster/filemaster-core 2>/dev/null >&2 || :
fi

echo "[ ] Stopping and disabling service"
systemctl stop filemaster.service
systemctl disable filemaster.service

echo "[ ] Removing files"
# Remove binaries folder
rm -fr /opt/filemaster
# Remove data folder
rm -fr /var/lib/filemaster
