#!/bin/bash

echo "[ ] Post-Install script [arg1='$1' arg2='$2']"

#
# Fix selinux permissions for portmaster-core if we have semanage available.
#
if command -V semanage >/dev/null 2>&1; then
    echo "[ ] Fixing SELinux permissions"
    semanage fcontext -a -t bin_t -s system_u /opt/filemaster/portmaster-core || :
    restorecon -R /opt/filemaster/portmaster-core 2>/dev/null >&2 || :
fi

echo "[ ] Initializing binary files"
mv /usr/bin/portmaster /opt/filemaster/portmaster
ln -s /opt/filemaster/portmaster /usr/bin/portmaster

chmod +x /opt/filemaster/portmaster-core

echo "[ ] Enabling service"
systemctl daemon-reload
systemctl enable filemaster.service

echo "[ ] Done. Please reboot your system"
